# Generated by Django 6.0.3 on 2026-07-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feature_access',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
