# Generated by Django 6.0.3 on 2026-04-18 08:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_alter_productvariant_discount_percent'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shops.shop')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('upi', 'UPI'), ('qr', 'QR')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='shops.shop')),
            ],
            options={
                'db_table': 'billing_payment_configs',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('qr', 'QR')], max_length=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], max_length=10)),
                ('payment_config_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_config_value', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bills', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='shops.shop')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='sales.customer')),
                ('selected_payment_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='sales.paymentconfig')),
            ],
            options={
                'db_table': 'billing_bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='sales.bill')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='products.productvariant')),
            ],
            options={
                'db_table': 'billing_bill_items',
                'indexes': [models.Index(fields=['bill'], name='billing_bil_bill_id_ea3cbb_idx'), models.Index(fields=['product_variant'], name='billing_bil_product_f2ebd8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['shop', 'phone'], name='sales_custo_shop_id_cf21ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('shop', 'phone'), name='unique_customer_phone_per_shop'),
        ),
        migrations.AddIndex(
            model_name='paymentconfig',
            index=models.Index(fields=['shop', 'type', 'is_active'], name='billing_pay_shop_id_167268_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['shop'], name='billing_bil_shop_id_ccfd62_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_by'], name='billing_bil_created_9241ac_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['payment_status'], name='billing_bil_payment_5f0664_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_at'], name='billing_bil_created_4f7b62_idx'),
        ),
    ]
