# Generated by Django 6.0.3 on 2026-04-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentconfig',
            name='billing_pay_shop_id_167268_idx',
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('qr', 'QR')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='paymentconfig',
            index=models.Index(fields=['shop', 'is_active'], name='billing_pay_shop_id_801f9d_idx'),
        ),
        migrations.RemoveField(
            model_name='paymentconfig',
            name='type',
        ),
        migrations.RemoveField(
            model_name='paymentconfig',
            name='upi_id',
        ),
    ]
