# Generated by Django 6.0.3 on 2026-04-19 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariant_discount_percent'),
        ('sales', '0002_remove_paymentconfig_billing_pay_shop_id_167268_idx_and_more'),
        ('shops', '0001_initial'),
        ('vendors', '0003_vendor_email_vendor_gst_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('VENDOR_PAYMENT_DUE', 'Vendor payment due')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='products.productvariant')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shops.shop')),
                ('stock_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='vendors.stockentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'is_read', 'created_at'], name='sales_notif_shop_id_592aa6_idx'), models.Index(fields=['shop', 'type', 'is_read'], name='sales_notif_shop_id_050bdb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_read', False)), fields=('shop', 'type', 'product_variant'), name='uniq_unread_variant_notification_per_type'), models.UniqueConstraint(condition=models.Q(('is_read', False)), fields=('shop', 'type', 'stock_entry'), name='uniq_unread_stock_entry_notification_per_type')],
            },
        ),
    ]
