# Generated by Django 6.0.3 on 2026-06-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_bill_whatsapp_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bill',
            new_name='billing_bil_whatsap_146f99_idx',
            old_name='billing_bil_whatsap_0a8f2d_idx',
        ),
    ]
