# Generated by Django 6.0.3 on 2026-04-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_low_stock_alert_sent_once_and_more'),
        ('sales', '0003_notification'),
        ('shops', '0001_initial'),
        ('vendors', '0003_vendor_email_vendor_gst_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_unread_variant_notification_per_type',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_unread_stock_entry_notification_per_type',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='sales_notif_shop_id_592aa6_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='sales_notif_shop_id_050bdb_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='is_seen',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['shop', 'is_seen', 'created_at'], name='sales_notif_shop_id_38fb51_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['shop', 'type', 'is_seen'], name='sales_notif_shop_id_70172a_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_seen', False)), fields=('shop', 'type', 'product_variant'), name='uniq_unread_variant_notification_per_type'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_seen', False)), fields=('shop', 'type', 'stock_entry'), name='uniq_unread_stock_entry_notification_per_type'),
        ),
    ]
