# Generated by Django 6.0.3 on 2026-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_notification_uniq_unread_variant_notification_per_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PRE_LOW_STOCK', 'Pre Low Stock'), ('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('VENDOR_PAYMENT_DUE', 'Vendor payment due')], db_index=True, max_length=30),
        ),
    ]
