# Generated by Django 6.0.3 on 2026-07-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_billitem_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='settlement_direction',
            field=models.CharField(choices=[('customer_to_shop', 'Customer to shop'), ('shop_to_customer', 'Shop to customer'), ('none', 'None')], default='customer_to_shop', max_length=20),
        ),
        migrations.AddField(
            model_name='billitem',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
