# Generated by Django 6.0.3 on 2026-05-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PRE_LOW_STOCK', 'Low Stock Warning'), ('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('VENDOR_PAYMENT_DUE', 'Vendor payment due')], db_index=True, max_length=30),
        ),
    ]
