# Generated by Django 6.0.3 on 2026-05-16 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productvariant_pre_low_stock_alert_sent_once'),
        ('sales', '0006_alter_notification_type'),
        ('shops', '0002_shop_gst_number_shop_updated_at_and_more'),
        ('vendors', '0006_alter_stockentry_paid_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_unread_variant_notification_per_type',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_unread_stock_entry_notification_per_type',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='sales_notif_shop_id_38fb51_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='sales_notif_shop_id_70172a_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['shop', 'created_at'], name='sales_notif_shop_id_fbdcd4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['shop', 'type'], name='sales_notif_shop_id_db058d_idx'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='sales.notification'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_seen',
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together={('notification', 'user')},
        ),
    ]
