# Generated by Django 6.0.3 on 2026-05-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_notificationread_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='discount_amount',
            new_name='custom_amount',
        ),
        migrations.RenameField(
            model_name='billitem',
            old_name='discount_amount',
            new_name='custom_amount',
        ),
    ]
