# Generated by Django 6.0.3 on 2026-07-19 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_name'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntryTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.PositiveIntegerField()),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_top_ups', to='products.productvariant')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to='vendors.stockentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock_entry'], name='vendors_sto_stock_e_97be29_idx'), models.Index(fields=['product_variant'], name='vendors_sto_product_65aa7f_idx')],
            },
        ),
    ]
