# Generated by Django 6.0.3 on 2026-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='status',
            field=models.CharField(choices=[('partial', 'Partially Paid'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], db_index=True, default='unpaid', max_length=10),
        ),
    ]
