# Generated by Django 6.0.3 on 2026-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_stockentry_is_fully_paid_alter_stockentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
