# Generated by Django 6.0.3 on 2026-07-25 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_stockentrytopup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='vendors.vendorpayment')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='vendors.stockentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['vendor', 'payment_date'], name='vendors_ven_vendor__9da1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpaymentallocation',
            index=models.Index(fields=['payment'], name='vendors_ven_payment_7e3936_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpaymentallocation',
            index=models.Index(fields=['stock_entry'], name='vendors_ven_stock_e_3002f3_idx'),
        ),
    ]
