# Generated by Django 6.0.3 on 2026-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorpayment_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
