# Generated by Django 6.0.3 on 2026-04-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('vendors', '0003_vendor_email_vendor_gst_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('shop', 'phone'), name='unique_vendor_phone_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('shop', 'gst_number'), name='unique_vendor_gst_per_shop'),
        ),
    ]
