# Generated by Django 6.0.3 on 2026-05-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_unique_vendor_phone_per_shop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockentry',
            old_name='invoice_number',
            new_name='stk_number',
        ),
    ]
