# Generated by Django 6.0.3 on 2026-08-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_stockentry_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
