# Generated by Django 6.0.3 on 2026-05-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_rename_invoice_number_stockentry_stk_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
