# Generated by Django 6.0.3 on 2026-04-11 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_product_cee51f_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_product_66459e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_variants', to='vendors.stockentry'),
        ),
        migrations.AddField(
            model_name='size',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='size',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(fields=('name', 'shop'), name='unique_size_per_shop'),
        ),
        migrations.AddField(
            model_name='color',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'size', 'color'], name='products_pr_product_aa66c3_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['stock_entry'], name='products_pr_stock_e_cf46ea_idx'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.itemtype'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['item_type'], name='products_pr_item_ty_dab6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['shop'], name='products_co_shop_id_9dfcae_idx'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('name', 'shop'), name='unique_color_per_shop'),
        ),
        migrations.AddIndex(
            model_name='itemtype',
            index=models.Index(fields=['shop'], name='products_it_shop_id_65d8e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(fields=('name', 'shop'), name='unique_itemtype_per_shop'),
        ),
    ]
