# Generated by Django 6.0.3 on 2026-04-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color_itemtype_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_variants', to='vendors.stockentry'),
        ),
    ]
