# Generated by Django 6.0.3 on 2026-04-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_stock_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='qr_code_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
