# Generated by Django 6.0.3 on 2026-04-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_qr_code_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('boy', 'Boy'), ('girl', 'Girl')], max_length=10),
        ),
    ]
