# Generated by Django 6.0.3 on 2026-04-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
