# Generated by Django 6.0.3 on 2026-04-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant_original_price'),
        ('vendors', '0002_stockentry_is_fully_paid_alter_stockentry_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_qr_code_e75067_idx',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='qr_code_number',
            new_name='barcode_number',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='bar_codes/'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['barcode_number'], name='products_pr_barcode_b536f0_idx'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='qr_code_image',
        ),
    ]
