# Generated by Django 6.0.3 on 2026-04-18 08:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productvariant_products_pr_qr_code_e75067_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
