# Generated by Django 6.0.3 on 2026-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariant_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_alert_sent_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='out_of_stock_alert_sent_once',
            field=models.BooleanField(default=False),
        ),
    ]
