# Generated by Django 6.0.3 on 2026-04-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_low_stock_alert_sent_once_and_more'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop'], name='products_co_shop_id_c91825_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'shop'), name='unique_company_per_shop')],
            },
        ),
    ]
