# Generated by Django 6.0.3 on 2026-05-03 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_company'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_430731_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.company'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='products_pr_company_71d1d5_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='company_name',
        ),
    ]
