# Generated by Django 6.0.3 on 2026-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_products_pr_name_430731_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='pre_low_stock_alert_sent_once',
            field=models.BooleanField(default=False),
        ),
    ]
