# Generated by Django 6.0.3 on 2026-05-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='original_price',
            new_name='original_purchase_price',
        ),
    ]
