# Generated by Django 6.0.3 on 2026-06-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='default_low_stock_limit',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
